#!/bin/sh
# https://github.com/fabricionaweb/cloudflare-ddns

# settings
ZONE="domain.com"
RECORD="sub.domain.com"
# generate the API TOKEN in the dashboard https://dash.cloudflare.com/profile/api-tokens - Get a TOKEN not a KEY
TOKEN=""

# cloudflare api (dont need to change)
ENDPOINT="https://api.cloudflare.com/client/v4"

logger -t hotplug "Running DDNS on interface: $INTERFACE for action: $ACTION"

# only for wan interface and up/update actions
if [[ "$INTERFACE" = "wan" || "$INTERFACE" = "wan6" ]] && [[ "$ACTION" = "ifup" || "$ACTION" = "ifupdate" ]]; then
  if [ "$INTERFACE" = "wan" ]; then
    URL="1.1.1.1"
    TYPE="A"
  fi

  if [ "$INTERFACE" = "wan6" ]; then
    URL="[2606:4700:4700::1111]"
    TYPE="AAAA"
  fi

  # gets the ip from internet
  NET_ADDR=$(curl -sS -X GET "https://$URL/cdn-cgi/trace" | awk -F '=' '/ip/{print $2}')
  logger -t hotplug "IP address: $NET_ADDR"

  # wait for dns be ready
  sleep 30

  # gets the domain zone id
  # https://api.cloudflare.com/#zone-list-zones
  ZONE_ID=$(curl -sS -X GET "$ENDPOINT/zones?name=$ZONE" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" | jsonfilter -e "@.result[0].id")

  # gets the dns record id
  # https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
  RECORD_ID=$(curl -sS -X GET "$ENDPOINT/zones/$ZONE_ID/dns_records?name=$RECORD&type=$TYPE" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" | jsonfilter -e "@.result[0].id")

  # updates the dns record
  # https://api.cloudflare.com/#dns-records-for-a-zone-patch-dns-record
  RESULT=$(curl -sS -X PATCH "$ENDPOINT/zones/$ZONE_ID/dns_records/$RECORD_ID" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    --data "{\"content\":\"$NET_ADDR\"}" | jsonfilter -e "@['success','errors','messages']")

  logger -t hotplug "Result: $RESULT"
fi
