#!/bin/sh
# https://github.com/fabricionaweb/cloudflare-ddns

# settings
ZONE="domain.com"
RECORD="sub.domain.com"
# you can generate the API Token on dashboard
# https://api.cloudflare.com/#getting-started-requests
TOKEN=""

# cloudflare api (dont need to change)
ENDPOINT="https://api.cloudflare.com/client/v4"

logger -t hotplug "Running DDNS on interface: $INTERFACE for action: $ACTION"

# only for wan interface and up/update actions
if [ "$INTERFACE" = "wan" ] && [[ "$ACTION" = "ifup" || "$ACTION" = "ifupdate" ]]; then
  # gets the ip from WAN (works only in bridge mode)
  # https://openwrt.org/docs/guide-developer/network-scripting#get_wan_address
  # . /lib/functions/network.sh
  # network_flush_cache
  # network_find_wan NET_IF
  # network_get_ipaddr NET_ADDR "$NET_IF"
  # logger -t hotplug "IP address: $NET_ADDR"

  # gets the ip from internet
  NET_ADDR=$(curl -sS -X GET "https://1.1.1.1/cdn-cgi/trace" | awk -F '=' '/ip/{print $2}')
  logger -t hotplug "IP address: $NET_ADDR"

  # wait for dns be ready
  sleep 30

  # gets the domain zone id
  # https://api.cloudflare.com/#zone-list-zones
  ZONE_ID=$(curl -sS -X GET "$ENDPOINT/zones?name=$ZONE" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" | jsonfilter -e "@.result[0].id")

  # gets the dns record id
  # https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
  RECORD_ID=$(curl -sS -X GET "$ENDPOINT/zones/$ZONE_ID/dns_records?name=$RECORD" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" | jsonfilter -e "@.result[0].id")

  # updates the dns record
  # https://api.cloudflare.com/#dns-records-for-a-zone-patch-dns-record
  RESULT=$(curl -sS -X PATCH "$ENDPOINT/zones/$ZONE_ID/dns_records/$RECORD_ID" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    --data "{\"content\":\"$NET_ADDR\"}" | jsonfilter -e "@['success','errors','messages']")

  logger -t hotplug "Result: $RESULT"
fi
