services:
  cron:
    image: ghcr.io/fabricionaweb/cloudflare-ddns
    restart: unless-stopped

    # env_file: .env
    environment:
      # https://crontab.guru/every-15-minutes
      - CRON_TIME=*/15 * * * *

      # Your Cloudflare email and the api token
      # https://developers.cloudflare.com/api/tokens/create/
      - API_USER=
      - API_KEY=
      # The domain where your dns belongs (zone)
      #   domain.tld
      - DOMAIN=
      # The dns that you want to update (record)
      #   sub.domain.tld
      - DNS=
